language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: cjdymj7YJNFEGziXRtK+CU0eL3KmPiNAyi3hNevKJMKHaD51Q1utv7sJoo/giRM+/zivL/gAQryB1Yt6GUexjYOUsLo/eQYgapdNTPPYVKAV2WmDFBSauHGGhtO5hOsEWKU3kWtfYQ7GsCAqTU8kEMilzW5eNfRejjzJhk8UckaqgLFznel9pKLw3WvtixV9LHrYJZXqFf3CNpMFvSCcNg9LH5fdfmzxHdO9O53XLaWEEHpUHjhRgqUQy+/fcJ/CtaH9kCI9GPV3tpsKch2QhbSmHG5DHs4nokx+Fs7Vp7zuSn/DbEAr7KvceZx6LEs2ZBtmQvkBE11tHDvhQE6KvRg1Fa64xbCSeYDWhZpLg2PIecZXHAh59wHdtflvkyI+9RgHyducjQLuCgPfPd1LssztJuNYgowcMPbkE991rwr71Jf//qTg1auhY1ElOftEz9ZQrM3qYU2GlvZbotRLg6sNoY1Naax/+YLzw2tjJ3h4FeNImICKaNg75BGZ7ayC9PZBHWg7muyffxwYYZzczlVs6ybWu05jwdahQPHhwXJbBYXo9smlkAAPHCtXqe5tqDPwTxjEu8iPjB/ZqjVmRcgGsx5QEjt8RBFUYKXOCAto5Psxg5NPcFS2iFmeU/wzID5qCBdwL/z53RHaSmu6B0xnDnDTqx4lLJD/X0ouHwg=
  app: mongoose-integration-testing
  on:
    repo: Vlodnik/mongoose-integration-testing
